on: [push]
name: Integration Tests
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ["9.8", "9.6", "9.4"]
        cabal: ["3.4", "3.6", "3.8", "3.10"]
    name: Integration Tests
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: "cabal run AdventOfCode -- puzzle all | tee integration.produced"
      - run: cat integration.snapshot 
      - run: cat integration.produced
      - run: cmp integration.snapshot integration.produced


